name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.2.3
  - pip=20.3.3
  - scikit-learn=0.24.1
  - matplotlib
  - plotly
  - pillow=8.1.2
  - mlflow=1.14.1
  - pip:
      - wandb==0.10.21
      - omegaconf==2.0.6